### ISSUE TITLE
Camera selection and integration

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#10]
What cameras do we currently have in Resistor? Take stock! Hopefully we'll have one to repurpose but, if not, this issue should have to tracking down a camera to feed our computer vision. After that, you'll need to work in cahoots with the flag/neckpiece crafters and computer vision to see if IR is necessary or what color LEDs will work best.  IR may require the removal of an internal camera filter.

Playstation Eyetoys are cheap and well documented for general hackery.

**Comment by moonmilk** [comment]
I've got an eyetoy and a surprisingly good [Microsoft Lifecam Studio](https://www.microsoft.com/hardware/en-us/p/lifecam-studio) if you want to use either of those. Would prefer not to IR-hack them, though.

**Comment by bjornsen** [comment]
@jqpubliq feel free to take this issue assignment.

@moonmilk Ryan is going to be investigating flag design with his connect and see if it can be used as a standard Linux video device. If not, we'll likely jump on one of your multitudinous cameras.

**Comment by jqpubliq** [comment]
Going to try to get the Kinect working on my laptop in a VM.  Failing that, I have an old (2006-era?) laptop at Resistor that I can throw a basic linux distro on and use that directly.  I don't think we'll need much horsepower to run it.  Ranjit, if you want to try the eyetoy also, let me know; happy to meet up at the space and muck around.

**Comment by wwward** [comment]
I have a PS3 eye with the IR filter removed.  It was hanging over the table at Resistor for a long time, it's probably been stowed since.  I installed a visible light filter so that it only passes common IR spectra (850nm?) and works lovely with OpenCV.

**Comment by bjornsen** [comment]
Looking for something that isn't a Kinect or PS3 eyetoy with a wide field of view. Widget says he may have one with 120 degrees in his office.

**Comment by widget1985** [comment]
I've acquired the webcam!  it's not 120 degrees but 90, it's a Logitech C930e HD Webcam.  It's also Tripod-mountable.  I'll bring it in next craft night.

**Comment by jqpubliq** [comment]
That should be plenty.  By my math, 90 degrees of horizontal view means that we only need a depth of about 3.5 feet to view a horizontal width of 10 feet.  So at a depth of maybe 8 feet, we should be golden for height and width.

**Comment by jqpubliq** [comment]
C930e is playing nicely.  Field of view is great.  Have to remember to tweak Logitech cam settings to match the environment when we get there.
