### ISSUE TITLE
Booth Engineering

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#12]
Backdrop
Computer placement
Tables
Interfacing with the Makerfaire people to make sure we get a placement where we can be successful! We ideally need to be inside, facing a wall, with relatively static ambient light.

**Comment by jqpubliq** [comment]
Duvetyne is in the space.  Top row, second column from the left in Squaresville.  Lindsay is working on finding a convention backdrop stand in case we don't have a wall behind us.

**Comment by jqpubliq** [comment]
Contacted Maker Faire with requests re light and space.  Told them we need a space indoors, preferably against a wall, big enough to wave flags around without hitting neighbors and without traffic getting between the player and the camera.  They responded to @osresearch with an acknowledgement.

**Comment by bjornsen** [comment]
I created a wikispace in our GitHub to start storing extra information
about Makerfaire, repair kits, etc...

Added the Makerfaire links and email confirmation in there so far.

**Comment by bjornsen** [comment]
Splitting the booth engineering (positioning, lighting, interfacing with Makerfaire) from the more artistic design aspects.
