### ISSUE TITLE
Marketing campaign

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#14]
Tweet about that terrible case of scurvy you came down with one time.

**Comment by bjornsen** [comment]
Specifically, blog posts/twitter/general awareness. Talk to Colleen about graphics/design stuffs

**Comment by huertanix** [comment]
:+1:

**Comment by huertanix** [comment]
Facebook linkage: https://www.facebook.com/NYCResistor/photos/a.614673808575005.1073741828.199215933454130/964865720222477/?type=3&theater.

Twitters:
https://twitter.com/nycresistor/status/646467548318429184

**Comment by huertanix** [comment]
Moooooar: https://twitter.com/nycresistor/status/647228441373343744.

**Comment by huertanix** [comment]
On Google Plus now, p sure it's gonna go viral: https://plus.google.com/104306218032212377514/posts/PjPmv2XY8gd.
