### ISSUE TITLE
Instagram Integration

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#17]
Post a photo-collage of all the letters a person signaled.

**Comment by jqpubliq** [comment]
Instagram officially doesn't allow posting of images through their API per https://instagram.com/developer/endpoints/media/

"At this time, uploading via the API is not possible. We made a conscious choice not to add this for the following reasons:

Instagram is about your life on the go – we hope to encourage photos from within the app.
We want to fight spam & low quality photos. Once we allow uploading from other sources, it's harder to control what comes into the Instagram ecosystem. All this being said, we're working on ways to ensure users have a consistent and high-quality experience on our platform."

**Comment by jqpubliq** [comment]
If we want to do Instagram integration, we'd have to do it manually on our own account with other users tagged, perhaps.
