### ISSUE TITLE
Configure camera to filter LEDs to usable color range

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#21]
Could be physical or software filter

**Comment by jqpubliq** [comment]
72mm variable neutral density filter is in Squaresville, top row, second column from the left.  Should be all the filter we need and then some.  Can use helping hands to hold it in front of the camera.

**Comment by jqpubliq** [comment]
Filter works with third hand.  Need to adapt white balance settings to the local ambient light using the Logitech camera app from the Mac App store.
