### ISSUE TITLE
Create mockup sketch for ideal islander

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#22]
A beautifully drawn maroonee that we can model in Unity.  Colleen to offload to Olivia or Ariel

**Comment by colleenaf** [comment]
Making sure I understand this one. We just need a pencil sketch, right? Are we thinking of a particular style? Like more cartoon-y or more realistic? Is this mostly about the outfit or the actual look of the person? Why is the sky blue? Do fish sleep? Where are my pants?

**Comment by bjornsen** [comment]
Consult with Widget for further details but my sense is a pencil sketch is
perfect and the styling is in your hands

**Comment by widget1985** [comment]
Yep.  I'm looking for some concept sketches to get an idea what our allot
should look like.

**Comment by jqpubliq** [comment]
Islander appropriately scurvy and asymmetrically panted.
