### ISSUE TITLE
Create Illustrator words for insults/text

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#23]
Save as PNGs for import to Unity

**Comment by colleenaf** [comment]
Stripped down my computer and I now have abobe programs again. YAY! 

Anyone have a preference on fonts? I was suggesting Badaboom yesterday, which is more of a fighter-game font, but maybe we want something that feels more island/nautical/campy. Here are some choices. Let me know if you have a fav. 
http://www.myfonts.com/album/881086/

**Comment by jqpubliq** [comment]
W00t working machine!

The font album is "not public", says the error message.

**Comment by colleenaf** [comment]
The font album was just being shy. (or you know I forgot to click the "outsiders" box)

Should be good to click now!

**Comment by jqpubliq** [comment]
I mean, Exotic Island has its name going for it.  And it's aptly named.  Men of Science also seems solid.  I like Always Angry for the negative status messages.

**Comment by bjornsen** [comment]
I'm liking Volcano for the Title screen (something like "The Jungle Cafe"
demo text)
Bornholm or Men of Science if we have reading text/instructions/scrolling
anything
Always Angry or Astounder Squared for status messages

Do you already have the fonts or are you dropping bucks on these? If the
latter, I'm happy to chip in but it'll help set the overall number of fonts
we'll choose. Speaking of which, how many different text types are we
expecting and how many different fonts should there be to make things look
coherent?

**Comment by colleenaf** [comment]
Number of fonts: 
Whatever I use to make Logo (no more than 2, and likely some handmade elements, perhaps all handmade in illustrator) 
1 for TO BE SIGNED text scrolling (SOS HELP, etc), needs to be clear and readable (might be the same as GOOD encouragement font if that one is clear enough)
1 for GOOD encouragements, fun campy!
1 for BAD encouragements, scary looking baaad! 

I own half of these, but will likely use this as an excuse to buy one or two more fonts. I like those sort of excuses. Someone buy me a bubble tea at some point and we'll all be even. Also I'm sure you guys are spending monies as well.

**Comment by colleenaf** [comment]
General look below. Went super camp with encouragements and dark with discouragements. Here are all the words in high res: http://furboajerboa.com/assets/images/2015/SemaphoreHero/

I can easily add or subtract or change overall look of any of these. 

![semaphoretextgoodwords-01](https://cloud.githubusercontent.com/assets/13964937/9896249/322ceb3e-5c07-11e5-890f-3b0ecec8d9e4.png)


![semaphoretextbadwords-08](https://cloud.githubusercontent.com/assets/13964937/9895988/39199166-5c04-11e5-9eb8-dbc7cdba47f6.png)


![semaphoretextgameplay-21](https://cloud.githubusercontent.com/assets/13964937/9895949/bc8b6232-5c03-11e5-9e24-b8f87eb4150b.png)

**Comment by jqpubliq** [comment]
I've been working on the assumption of having five error levels of praise/taunt.  That's easily changeable, but the image assets will need to match up with the error level code.

**Comment by colleenaf** [comment]
How about: 

BAD:
Level 1 - MISS! 
Level 2 - BOO!
Level 3 - SHARK FOOD!
Level 4 - TITANIC!
Level 5 - ARE YOU EVEN TRYING? 

GOOD: 
Level 1 - NICE!
Level 2 - AWESOME!
Level 3 - NAUTICAL!
Level 4 - ALBATROSS!
Level 5 - ARE YOU BEYONCE?!

Do you want me to have Level 4 and 5 on each good/bad spectrum be significantly different looking?

**Comment by bjornsen** [comment]
Since we're operating under the assumption right now that there will be 45 degrees of error, let's go with either 5 or 9 feedback words + the complete MISS (e.g. ARE YOU EVEN TRYING!?). This will divide out feedback into clean integer buckets.  In total it would look like

4 (or 2) GOOD
1 NEUTRAL
4 (or 2) BAD

1 COMPLETE FAIL

Coordinate with Widget on colors for the text displays. My intuition is that the yellow border with light blue interior on NAUTICAL! won't stand out against a sandy island with beautiful tropical skies.

I love the Titanic fail!

**Comment by jqpubliq** [comment]
Right, we can use (Floor(TotalError / 5)) as a mapping function.  So let's use Colleen's list with 9 error levels for poses that are recognized as a letter, and a tenth level for a pose that doesn't even parse into a letter:

0 (perfect) - ARE YOU BEYONCE?!
1 - ALBATROSS!
2 - NAUTICAL!
3 - AWESOME!
4 - NICE!
5 - MISS! 
6 - BOO!
7 - SHARK FOOD!
8 - TITANIC!
NoLetter - ARE YOU EVEN TRYING?

**Comment by colleenaf** [comment]
I was imagining the ARE YOU BEYONCE?! or ARE YOU EVEN TRYING? being score based not individual sign based so they wouldn't show up too often. For instance if you got 5 letters perfect in a row THEN you get the beyonce comment, and vice vesa with 5 letters wrong in a row. If that's not possible I think we should make the worst one "FLAG FAIL" and the best one "NAUTICAL!" and re-add the "GREAT JOB" in there. 

Got background from Widget. Will do some mocks to make sure type looks good.

**Comment by bjornsen** [comment]
I moved OK in at the "neutral" position to better delineate between the good and bad sections, and added ALMOST as encouraging negative feedback. MISS, to me, says that you weren't close. I also pared the exclamation points down to the couple best and worst:

0 - NAUTICAL!
1 - AWESOME!
2 - GREAT JOB
3 - NICE
4 - OK
5 - ALMOST
6 - BOO
7 - SHARK FOOD!
8 - TITANIC!

NoLetter - FLAG FAIL!
5 NAUTICAL in a row - ARE YOU BEYONCE?!

@colleenaf is this closer to your vision? Please swap around and substitute any of the wording as you see fit.

**Comment by colleenaf** [comment]
Works great for me! I'll come up with a look for the three neutral ones and will try all with the background tonight.

**Comment by colleenaf** [comment]
Adjusted! Now with more neutral. only change I made was adding a "MEH" instead of "OK" because I love the idea of the game not really caring how badly you are doing. Here they all are in high-res form, labeled by level of accuracy: 

http://furboajerboa.com/assets/images/2015/SemaphoreHero/AccuracyFeedback/
