### ISSUE TITLE
Create OSC server for receiving flag data on game server

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#24]
@nickvermeer will create a basic configuration for both server and client in C/C++. We need a C# server to integrate properly in the game.

**Comment by widget1985** [comment]
Pretty much done thanks to https://github.com/jorgegarcia/UnityOSC. I just need to know Address and data types.

**Comment by bjornsen** [comment]
Hmm, since you'll be the server, you shouldn't need to configure an address
(though it will be localhost).  Looking through those docs, I think all you
need is to create a server in the OSCHandler and have a small loop that
performs the log update then grabs the message Dictionary and prints the
info. That should be everything we need to at least confirm the setup is
working.
