### ISSUE TITLE
Hardware to run everything on

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#27]
Target is Mac/OSX. Bill has a 7 year old Macbook with Snow Leopard that we might be able to use. @jqpubliq is emailing the list for donations.

**Comment by jqpubliq** [comment]
Widget may have a Mac Mini to contribute.  Checked the fabric shelf and saw a Mac Mini that may belong to Justin; unclear whether it is available.

**Comment by jqpubliq** [comment]
Justin says we can use his Mac Mini in a pinch.  Not sure whether Widget's potential Mini is available.

**Comment by widget1985** [comment]
I'll try to remember to bring the target machine in tonight. Hopefully a 5 year old mac mini is enough to do the jorb.
