### ISSUE TITLE
Game Logo

### ISSUE THREAD

**Issue by colleenaf** [nycresistor/Semaphore-Hero#31]
Some rough-ish test options of what I've been thinking. The more caffeine I consumed while making these the bigger the flag flames seemed to get. Numbered for ease of talkin'.

![semaphorelogotest-05](https://cloud.githubusercontent.com/assets/13964937/10036858/afe1fa5a-617b-11e5-8f94-0334bbc39b7f.png)
![semaphorelogotest-04](https://cloud.githubusercontent.com/assets/13964937/10036859/afe704a0-617b-11e5-832e-69a8aa109c8f.png)
![semaphorelogotest-03](https://cloud.githubusercontent.com/assets/13964937/10036862/affffc44-617b-11e5-96f3-743340ce1909.png)
![semaphorelogotest-02](https://cloud.githubusercontent.com/assets/13964937/10036861/affbcb7e-617b-11e5-9bb4-d1555fca528a.png)
![semaphorelogotest-01](https://cloud.githubusercontent.com/assets/13964937/10036860/aff9e098-617b-11e5-9374-62930473ce83.png)

**Comment by jqpubliq** [comment]
Love #4 and #1.  Looking great.  Would it be possible to print a few logo stickers small-ish?  I'd love one for the laptop.

**Comment by huertanix** [comment]
I really like 4, might be cool to have an island (sand mound+palm tree?) above the water line.

**Comment by colleenaf** [comment]
#4 is my fav as well. I'll tweak it to purdiness and do an island variation tonight. Part of me also wants to try and see what it looks like with shark teeth coming up around the bottom border. I will attempt to not go overboard. (Har har) 

Ryan: I'll totally make stickers of this along with the DEAD NOT DEAD stickers. Your laptop is gonna be so stylish.

**Comment by bjornsen** [comment]
#4 makes me want to be cast away on a desert island with a stockpile of
flags and a large drum of lighter fluid.

+1 4 #4

**Comment by colleenaf** [comment]
Getting closer. Vote or forever hold a palm tree!

![semaphorelogo3-04](https://cloud.githubusercontent.com/assets/13964937/10060337/42ccc3fc-621e-11e5-993b-8e0d4268e1bb.png)
![semaphorelogo3-03](https://cloud.githubusercontent.com/assets/13964937/10060338/42cd4606-621e-11e5-8210-760179c84d98.png)
![semaphorelogo3-02](https://cloud.githubusercontent.com/assets/13964937/10060340/42d0c74a-621e-11e5-8b8c-ead5291827db.png)
![semaphorelogo3-01](https://cloud.githubusercontent.com/assets/13964937/10060339/42cfe974-621e-11e5-9c5a-e59683909d1b.png)

**Comment by jqpubliq** [comment]
<3 6

**Comment by bjornsen** [comment]
!SIX SIX SIX!

**Comment by huertanix** [comment]
+6

**Comment by colleenaf** [comment]
Woot! My fav as well. Nice idea, David! Here it is in high-res no-background png form for plopping in the game. I have it as vectors if that's easier, Widget. 

![semaphorelogofinal-01](https://cloud.githubusercontent.com/assets/13964937/10061475/1e8230dc-6227-11e5-89b4-b063cc87a573.png)
