### ISSUE TITLE
Physical Flag Design

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#8]
We need flags that can be detected by our camera and computer vision. Th current thought is to use a set of colored LEDs or IR emitters positioned along the rigid material used to hold the flag. Or maybe for visibility's sake, they're better capped on each end.  Work with the camera person (or take that issue yourself!) to ensure we'll get continuous detection of the flag orientation.

**Comment by jqpubliq** [comment]
Got actual sempaphore flags.  Going to put LEDs on the ends to make them more obvious to the camera.

**Comment by wwward** [comment]
I have flat-faced T5 IR LEDs suitable for motion tracking on my shelf.

**Comment by jqpubliq** [comment]
Flags are ready for use.  There are possible improvements, but these will do fine for a couple days of use.  For repair sake if necessary, the red flag runs with a 1.9v drop on two AAs with a 15 ohm resistor.  The green flag runs on three AA cells with a voltage drop of 2.7-2.9v and has a 33 ohm resistor.
