### ISSUE TITLE
Super cool neck garb

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#9]
To determine a flag's current position and orientation, it'll be really handy to locate a person's center mass.  Sailor bibs, anchor necklaces, and/or an albatross around the neck all fit the bill and would conceal a different light/IR emitter (ideally, obviously different than the flags) nicely.

**Comment by jqpubliq** [comment]
Ordered a classic orange life vest and built the blue LED pack for the Heart of the Sea.  Should be functional for testing on Tuesday 9/15/15.  @colleenaf may have decorative ideas to theme it up.

**Comment by colleenaf** [comment]
Owns bedazzler. Will travel. 

Looked up some pictures and it seems really easy to add white gems around the LED and fake 
"necklace" strings attached to the life vest. I can make a trip to Michael's tonight for some gaudy craftin.

**Comment by bjornsen** [comment]
Is "Titanic!" one of our qualitative feedback terms?

**Comment by colleenaf** [comment]
It is now!

**Comment by jqpubliq** [comment]
Something like this, but will have to figure out a somewhat bigger surround to cover up the circuit board that pokes out behind the LED dome.  Thinking I'll laser cut the surround for bedazzling and hot glue the surround over the dome.

![image](https://cloud.githubusercontent.com/assets/1637574/9919990/9df98862-5c9e-11e5-98be-20e8d56c6797.png)

**Comment by colleenaf** [comment]
I'll bring all sorts of gaudy gems tonight and my bedazzler. This heart will go on! (the person playing the game's body)

**Comment by jqpubliq** [comment]
Velcro and hot glue.  Could use a little more glitz around the neck, but we're calling it done at least for now.
